/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitersRouteImport } from './routes/waiters'
import { Route as TakeOrderRouteImport } from './routes/take-order'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WaitersRoute = WaitersRouteImport.update({
  id: '/waiters',
  path: '/waiters',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeOrderRoute = TakeOrderRouteImport.update({
  id: '/take-order',
  path: '/take-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/take-order': typeof TakeOrderRoute
  '/waiters': typeof WaitersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/take-order': typeof TakeOrderRoute
  '/waiters': typeof WaitersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/take-order': typeof TakeOrderRoute
  '/waiters': typeof WaitersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/billing'
    | '/customers'
    | '/kitchen'
    | '/menu'
    | '/settings'
    | '/tables'
    | '/take-order'
    | '/waiters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/billing'
    | '/customers'
    | '/kitchen'
    | '/menu'
    | '/settings'
    | '/tables'
    | '/take-order'
    | '/waiters'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/billing'
    | '/customers'
    | '/kitchen'
    | '/menu'
    | '/settings'
    | '/tables'
    | '/take-order'
    | '/waiters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  CustomersRoute: typeof CustomersRoute
  KitchenRoute: typeof KitchenRoute
  MenuRoute: typeof MenuRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
  TakeOrderRoute: typeof TakeOrderRoute
  WaitersRoute: typeof WaitersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiters': {
      id: '/waiters'
      path: '/waiters'
      fullPath: '/waiters'
      preLoaderRoute: typeof WaitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take-order': {
      id: '/take-order'
      path: '/take-order'
      fullPath: '/take-order'
      preLoaderRoute: typeof TakeOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  CustomersRoute: CustomersRoute,
  KitchenRoute: KitchenRoute,
  MenuRoute: MenuRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
  TakeOrderRoute: TakeOrderRoute,
  WaitersRoute: WaitersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
